### ISSUE TITLE
Support native check spelling 

### ISSUE THREAD

**Issue by brunolimawd** [careteditor/caret#104]
Has any configuration for spell check to my language? 
Or Caret only works with English?

Example: 'Cão', dog in portuguese, is checked wrong.
![pt-br](https://cloud.githubusercontent.com/assets/350262/17790539/43ca3b1a-656d-11e6-8e0b-e04a516732cb.jpg)

OS X Preferences > Keyboard > Text > Spelling > Brazilian  Portuguese 

Caret 1.5.3
OS X 10.11.6

**Comment by astoilkov** [comment]
Hi,

Does the spell check starts working after you enter couple of sentences in portuguese? We have an issue where our language detection needs a few words to start recognizing the language correctly - before that it defaults to English.

Sorry for the long delay.

**Comment by brunolimawd** [comment]
Hi Antonio,

I transcribed the wikipedia these two paragraphs, and all the word in Portuguese are marked as wrong.

> Brasil, oficialmente República Federativa do Brasil, é o maior país da América do Sul e da região da América latina, sendo o quinto maior do mundo em área territorial e população.

> É o único país da América onde se fala majoritariamente a língua portuguesa e o maior país lusófono do planeta.

![screen shot 2016-09-26 at 13 35 11](https://cloud.githubusercontent.com/assets/350262/18843305/9312966e-83ee-11e6-8c93-a945d0b8270e.png)

😕

**Comment by borekb** [comment]
Out of curiosity, which dictionary does Caret use on Windows? Its own? Some other? (I don't think there's a system-wide dictionary like on Mac but I may be wrong.)

**Comment by astoilkov** [comment]
@brunolimawd -  We use the system dictionary on darwin so it is possible you don't have the language downloaded on your system. We will investigate further and let you know. Do you have similar problems on other applications or it is just Caret?

@borekb - On Windows it depends on what version you are. Windows 7 and below doesn't have a system-wide dictionary and we use custom one. However, Windows 8 and 10 have [Spell Check API](https://msdn.microsoft.com/en-us/library/windows/desktop/hh869853(v=vs.85).aspx) and we use it.

**Comment by astoilkov** [comment]
@brunolimawd We have found the reason for this behavior. This will be fixed in the next version of Caret. I will post in this thread when this happens.

**Comment by astoilkov** [comment]
Hi @brunolimawd,

We have fixed the described issue in the latest Caret 1.7.0 version. Could you update and try if your issue is fixed?

Thanks in advance.

**Comment by brunolimawd** [comment]
Hi @astoilkov,

Now it is working perfectly :smiley:

Thanks so much

**Comment by astoilkov** [comment]
Great to hear!

Closing this issue.

**Comment by borekb** [comment]
Hmm, still problematic in 1.7:

![image](https://cloud.githubusercontent.com/assets/101152/19132765/7159c61e-8b55-11e6-8544-abd794f1fa4d.png)

Should I open a new issue?

**Comment by astoilkov** [comment]
Hi @borekb,

The case under Windows is different. Most commonly Windows doesn't have more than one language on the system. In order for Caret to spellcheck all languages there are two possibilities:
  - We could include all languages inside of the app: this isn't much of an option because it will make the app 200 MB which is a lot for a text editor
  - Smarter option which we will eventually implement: We will detect the language you are writing on and if you don't have dictionary for it we will prompt you to download one

**Comment by borekb** [comment]
I'm not familiar with how exactly Windows provide spell checking services (and I'm quite surprise that they do because in most apps like Firefox, Chrome, Word, several text editors etc. I need to maintain multiple custom dictionaries which is a pain).

I have two languages installed:

![image](https://cloud.githubusercontent.com/assets/101152/19146696/e67bb4fc-8bb4-11e6-9840-092fe97069a6.png)

What is strange is that Caret sometimes doesn't highlight Czech words as misspelled, sometimes it does. I didn't work out what's causing one behavior or the other.

BTW where are my custom words stored? In some global Windows dictionary, or in some local Caret config?

**Comment by astoilkov** [comment]
We will investigate spellchecking under Windows further.

Regarding where custom words are stored: It depends on the version of Windows but in your case they should be stored in the global Windows dictionary.

**Comment by borekb** [comment]
BTW for users writing in multiple languages, newer versions of Chrome approach this right: they spell-check against **both dictionaries** at once ([blog post](http://thenextweb.com/google/2015/08/22/chrome-can-now-spellcheck-multiple-languages-simultaneously/)). Surprisingly few apps do this and if the Windows API offers this somehow, it would be really great to have this.

**Comment by astoilkov** [comment]
We are actually do the same thing. If we detect different language than english we spellcheck for both the detected language and english. However, we should improve the spellchecking of multiple languages in Windows and Linux.
