### ISSUE TITLE
Preview sometimes scrolls to the bottom when buffer is scrolled to the top

### ISSUE THREAD

**Issue by cttttt** [careteditor/caret#106]
# What do I do?  What happens?

- Fire up **Caret 1.5.4** and start editing a new file.
- Use Command-R to open the preview pane to the right of the buffer.
- Enter a few screen heights worth of Markdown.  Ensure that there are a few screen heights in both the buffer *as well as the preview*.
- Move the insertion point to the bottom of the buffer.
- NOTICE: The preview is scrolled all the way to the bottom of the document.
- Without moving the insertion point, use the trackpad to scroll the buffer to the top of the source.
- NOTICE: As the buffer is scrolled up, the preview also scrolls up.
- **ISSUE: As the absolute top of the buffer is reached, the preview pane scrolls all the way to the bottom.**

# What did I expect?

- The preview to remain scrolled to the top when the top of the buffer is reached.
- Alternatively, for the preview to always scroll to reveal the insertion point.

Not a super major bug, but a little annoying.  Hopefully it's a not-so-bad fix.  As always, lemme know if you need any more info.

~ chris

**Comment by astoilkov** [comment]
Hi @cttttt,

We made updates to the sync scrolling algorithm in the latest 1.6.1 Caret release. Could you update your app and check if the issue still persists?

**Comment by cttttt** [comment]
@astoilkov the original problem is definitely resolved:  If the insertion point is at the bottom of a multi-screen-height buffer, scrolling (with the mouse) to the top of said buffer *used to* scroll the preview all the way down to the bottom whereas now, it scrolls it up to the top with the buffer.  Perfect!

However I'm finding that if I scroll all the way to the bottom of the input buffer using the mouse, the preview scrolls *almost* to the bottom.  This is only a minor annoyance, though, since I can just manually scroll the preview down and I'm back in action.  Additionally, after this manual action, as I continue to enter text into the bottom of the input buffer, Caret makes no attempts at scrolling the preview, which is a-okay.

This isn't a big enough issue to open an additional bug, though.  And since this is done, I'm closing this off.

Hopefully all that made sense, and thanks a tonne for fixing these up so quickly!

~ chris

**Comment by astoilkov** [comment]
Great to hear the issue is now fixed.

The behaviour that you described as "a minor annoyance" is actually expected. Here what's happens:
   - you scroll to the bottom
   - when the cursor is not in view the preview is scrolled to align to the top line of the input view
   - you move the cursor to the end and now the preview is scrolled to align to the line where the cursor(caret) is

This only happens in certain use cases like having images in the end (as I suspect is your case).

We will leave this behaviour because it is very convenient in most cases and we will think if there is any solution for edge cases like yours.
