### ISSUE TITLE
1.5.4 - Preferences are not saving

### ISSUE THREAD

**Issue by lukehamburg** [careteditor/caret#110]
Just bought a license for Caret. Nice app! One thing I noticed was, every time I quit and launch the app, it resets the prefs to default.  Font size, SpellCheck on/off state, etc are all forgotten. Is this intentional for some reason? I would expect the prefs to be preserved.

I am on macOS Sierra 10.12 and using Caret 1.5.4

**Comment by astoilkov** [comment]
This seems to be a bug. I have tested on macOS Sierra 10.12 using Caret 1.5.4 but couldn't replicate the issue.

Does this happen with other apps? 
Could you check the following path and see if anything happens when changing preferences in the app - /Users/your-username/Library/Application Support/Caret/electron-cache. You could change to night mode and see if the "editor" file will include "nightMode: true" text.

**Comment by lukehamburg** [comment]
I think this might have been caused by a corrupt settings file from an older version. I deleted the caches like you suggested and that seems to have worked. Thanks!

**Comment by astoilkov** [comment]
Great to hear. Closing this.

If you have any additional questions do not hesitate to open a new issue.
