### ISSUE TITLE
New app icon very dark in Windows 10

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#133]
Quiz question: is there a Caret icon in my taskbar or not? 😄 

![image](https://cloud.githubusercontent.com/assets/101152/19076801/846ed89a-8a4a-11e6-83ea-62d49010c90d.png)

**Comment by erusev** [comment]
Haha, right, we have an improved icon ready for the next release - it should provide a better contrast :)

**Comment by sguergachi** [comment]
I don't know if this should be a separate issue, but it seems relevant to this one so here goes. This is based on my personal opinion, but hopefully I can appeal to your design senses to argue this point.

I think the new icon is worse than the old one, both from a functional point of view as well as an aesthetic point of view.

First, here is what the _new_ icon looks like next to other windows icons on my black taskbar (which I think is the default on Windows 10) compared to the _old_ one.

**un-selected NEW**

![current_icon](https://cloud.githubusercontent.com/assets/615386/19098897/3768f014-8a7f-11e6-91fa-26f033097539.PNG)


**un-selected OLD**

![old_icon](https://cloud.githubusercontent.com/assets/615386/19098899/3a038c80-8a7f-11e6-9bd7-2a5f64c6ae5c.PNG)


**selected NEW**

![selected_new_icon](https://cloud.githubusercontent.com/assets/615386/19098870/f3a16726-8a7e-11e6-9436-e1fc707fb176.PNG)

**selected OLD**

![selected_old_icon](https://cloud.githubusercontent.com/assets/615386/19098873/ff1ee9ca-8a7e-11e6-9331-0e46c0cd60b0.PNG)

So as we can see, the _old_ icon looks less visible than the _new_ one when _unselected_, I would argue that the blue cursor on the _old_ one does help, but not as much as the contrast of the gray box that is the _new_ icon.

For the _selected_ icon, I would say the _old_ icon is more visible than the _new_ one. You could argue that it matters less if the icon is visible when it's selected then when it's not, but you guys are in the business of obsessing over details right? :)

Anyways, from a functional point of view, I think the new icon does improve on initial visibility of the icon on a black taskbar _slightly_, but otherwise I think it's no better than the old one. If monochrome is the style you guys want to go with, then I suggest a white colored icon instead of the gray. It would make the app feel more at home/native on Windows (as you can see from the Windows Mail icon, and many other app icons).

From an aesthetic point of view, I really think the new icon suffers. The gray feels drab and depressing. And next to my other very colorful icons, it really shows. The old icon felt slick, and monolithic with the use of pure black, and the accented blue cursor really added to the sense of restraint and designed intent found within the app. It was really good is what I'm trying to say.

Now I can understand the need to change away from the black icon as much as I love it from the functional point of view. But I would be eternally grateful if you guys considered giving it another revision, for Windows especially. As I suggested, perhaps white would be the way to go if monochrome is the new style. I would personally still prefer a bit of color, like that gorgeous blue cursor. But I'll take anything I can get ;)  

Thank you guys for making such an awesome app, I really love it.

**Comment by astoilkov** [comment]
We have changed the icon under Windows in the new Caret 1.7.1 release. I hope you like it.

Closing this issue but feel free to comment or open a new issue if you still think there are problems with the icon.

**Comment by borekb** [comment]
After update from 1.7.0 to 1.7.1 (both still in my `%appdata%\caret` folder):

Start menu:

![image](https://cloud.githubusercontent.com/assets/101152/19191446/c7dcec34-8ca2-11e6-8db0-ef61ab522d7d.png)

Taskbar:

![image](https://cloud.githubusercontent.com/assets/101152/19191457/d42e9258-8ca2-11e6-9e5b-b80b006fddc3.png)

**Comment by astoilkov** [comment]
When experimenting with the app icons we had the same problem. It seems the updating of an app icon in Windows can't be controlled and it happens randomly. If you want to enforce the update of the icon you could follow the steps in [this article](http://www.windows10update.com/2015/05/windows-10-tutorials-80-how-to-rebuild-icon-cache/) (this worked for us).

**Comment by borekb** [comment]
Stupid question but what icon should I see with 1.7.1? After uninstalling and re-installing Caret, I see this in my taskbar:

![image](https://cloud.githubusercontent.com/assets/101152/19192515/bfe11cd6-8ca6-11e6-945e-423799e49536.png)

**Comment by sguergachi** [comment]
The "C" icon looks awesome guys. Fits perfectly. Glad you guys are open to iterating to make something better 👍🏻

**Comment by borekb** [comment]
The square icon is more "Caret-ish" (I got this motive imprinted into my mind after the installation process which is one of the coolest ones I've ever seen) but yes, it doesn't work too well on the taskbar.

**Comment by sguergachi** [comment]
I agree. And I'm sure they tried playing with the square icon a bunch before they landed on this. A white square icon might look bad perhaps. In any case, this icon is both clear and elegant, a net improvement I would say.

**Comment by erusev** [comment]
Thanks, we very much appreciate the feedback :)
