### ISSUE TITLE
No File menu on Linux

### ISSUE THREAD

**Issue by the4ndy** [careteditor/caret#154]
I am using Xubuntu 16.04 and I just installed Caret via the Deb file. It installed ok but there is no file menu. I recall on windows the top left corner was a menu that had options and such, that menu is not able to be found on my machine with a fresh caret install.

**Comment by astoilkov** [comment]
Does anything happen if you press the Alt key?

**Comment by the4ndy** [comment]
yup, that fixed it....any chance of implementing the gui file menu on linux like it is on Windows?

**Comment by astoilkov** [comment]
Yes this is possible. However, before we do that we should have a way of detecting what type of window the current linux distribution is creating. This is because some linux distributions are moving the menu outside of the window on OS level which is case when we shouldn't create a the menu inside of the window.
