### ISSUE TITLE
Q: how do I associate Caret with certain file type?

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#167]
I'd like to associate Caret with `.apib` files on Windows, how do I do that? Do I point to a specific version of Caret.exe? (I guess the association will become invalid once Caret autoupdates.) Do I point it to Update.exe?

Thanks.

**Comment by astoilkov** [comment]
I started investigating this. It turns out we should make an option in the "Open With" section where Caret will be associated with command that we should update every time the app updates. This will ensure you association is correct so it persists between versions.

We will try to implement this as soon as we complete other pending work.

**Comment by astoilkov** [comment]
In the latest Caret release 1.9.1 you should see Caret in the `Open With` menu. If you select it the reference will auto update on every Caret update.

Thanks for reporting this. Closing this issue.

If there is any problem with this do not hesitate to open a new issue.
