### ISSUE TITLE
Question: how does spell checking language detection work on Windows?

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#181]
I'd like to understand how language detection for spell checking works on Windows. I write mostly in English but sometimes in Czech. And sometimes, it picks up the right language, sometimes it doesn't. For example, if I write this by hand, I get a lot of spelling errors:

![image](https://cloud.githubusercontent.com/assets/101152/20829128/0c077f38-b87b-11e6-8138-2914b0f0eb3a.png)

If I paste similar content from clipboard, it is correct:

![image](https://cloud.githubusercontent.com/assets/101152/20829143/1ce9a394-b87b-11e6-81a6-86c8ae542228.png)

In this "correct" document, I can even mix Czech and English:

![image](https://cloud.githubusercontent.com/assets/101152/20829184/4bc7f6de-b87b-11e6-951c-22b256b0e9c3.png)

However, in the original document that I've entirely written by hand, Czech words are still recognized as spelling mistakes:

![image](https://cloud.githubusercontent.com/assets/101152/20829240/8e39ee14-b87b-11e6-8be3-296a9f807b32.png)

How does this work?

**Comment by astoilkov** [comment]
We have much work on the language detection in Caret. The problem in your case is that when you start typing in the beginning we can't detect the correct language because it is too little data and when we detect the correct language we don't go back to recheck all words with the new language.

We have few things in mind for the future to improve the experience:
   - [ ] Currently we check the entire document searching for one language. We think we should detect languages by paragraph so we could enable multilingual documents
   - [ ] We should detect the correct language even if it is only one word from that language
   - [ ] We could detect the languages that aren't available in the system and don't highlight every word as incorrect

**Comment by astoilkov** [comment]
This should now be resolved in the latest Caret 1.10.0 release.

Closing this issue.

**Comment by borekb** [comment]
I best like the multi-dictionary approach that Chrome implemented recently, i.e., if the word is in either of your dictionaries, it is fine. In other words, there's no strict distinction between "this document (or paragraph) is in this specific language".

Not sure if it's easy to implement but from the user point of view, I like this behavior best.

**Comment by astoilkov** [comment]
This is indeed a very good solution. Currently we have concerns because our spellcheck function calls C++ bridge which is a little slow and spellchecking for multiple languages could affect performance. However, we will definitely consider your suggestion.

Thanks!

**Comment by borekb** [comment]
Seems that 0.12 does multi-language spell checking, you guys rock!! ❤️
