### ISSUE TITLE
Path in window title

### ISSUE THREAD

**Issue by szepeviktor** [careteditor/caret#194]
Please consider adding an option (maybe under the Window menu)

*Show only file name in window title*

**Comment by erusev** [comment]
Is this because of file paths that are too long or because of something else? Thanks

**Comment by szepeviktor** [comment]
Of course because of the length.


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by sguergachi** [comment]
I think the solution should be to just make sure the file name is always visible. The name takes priority, the path is just a nice to have.

![image](https://cloud.githubusercontent.com/assets/615386/21468545/011be2c8-c9e5-11e6-9b3c-584e995b0221.png)

A nice way to do this could be to truncate the middle section of the path and have the two ends always be visible:

Original: C:/User/Sammy/Documents/Myfile.txt
Instead of truncating like this (current version): C:/User/Sammy/Document...
It could be like this instead (nice version): C:/User/.../Documents/Myfile.txt
Or like this (easy version): .../Sammy/Documents/Myfile.txt

**Comment by erusev** [comment]
@sguergachi Makes sense, we'll see what we can do.

**Comment by astoilkov** [comment]
This is now fixed in the latest Caret 4.0 Beta release available [here](https://caret.io/4beta/).

Closing this issue.
