### ISSUE TITLE
Multiple Selection broken

### ISSUE THREAD

**Issue by bdnk** [careteditor/caret#316]
Looks like the multiple selections feature behaves inconsistently. 

Clicking the end of one line, then option+clicking (Mac) the end of the line beneath it should place the cursor at the end of both lines. Instead it will either: 
- Just move the cursor to the new line, instead of placing a second one
- Do the same as above, but also multiple-select every line underneath it to the end of the file 

There doesn't seem to be any trigger for one behavior or the other, it seems to just randomly pick one.

Renders multiple select unusable. Should also add that having multiple select be mapped to command+click instead of option+click would give it the same mapping as Atom, which would be nice.

**Comment by astoilkov** [comment]
Adding another selection using the mouse could be achieved using `Cmd+Option+Click`. Have you tried this? Did you see it somewhere that multiple selections could be added with `Option+Click`?

We didn't make the combo `Cmd+Click` because sometimes when pasting content you would click the place you want to paste while already holding `Cmd` which results in pasting the clipboard data twice. However, we could add a keyboard shortcut configuration so users could chose their preference.

**Comment by bdnk** [comment]
Shortcut configurations would definitely be useful. I didn't see any
indications anywhere as to how to use the multiple select, so after trying
command+click, I tried option+click. I'm sure I won't be the only one to do
so. Cmd+Option+Click works well though, now that I know.

Would still look into that odd behaviour with option+click. Regardless of
how multiple select should work, option+click definitely shouldn't be doing
*that*.

Keep up the good work!

**Comment by astoilkov** [comment]
The issue with multiple cursors is now fixed in the latest Caret release.

Closing this issue. Thanks for reporting.
