### ISSUE TITLE
Disabling heading cues

### ISSUE THREAD

**Issue by ihackalot** [careteditor/caret#372]
Sorry about the title, I'm pretty sure the name is wrong. I mean the way headings are now displayed in Caret, which is neither the final rendering nor WYSIWYG. It's just huge characters written with some discretionary type. I'd like to be able to disable that:

- there's no balance between heading display size and the body
- there's actually no way to customize it
- it defeats the very basic principle of using semantic markup to render a structured document.

Please, if not remove it, at least let me disable it, as all my documents are mostly unreadable to me and I had to switch to a different editor.

**Comment by erusev** [comment]
Ok, we'll see what we can do.

**Comment by alinnert** [comment]
> it defeats the very basic principle of using semantic markup to render a structured document.

I can't agree here. The markdown you write is basically (some kind of) code. But that doesn't mean it mustn't look nice.
It heavily depends on how you use Caret and what you expect from it. If you write a novel I can imagine it's actually nicer to have a proportional font like this - for heading and body. There it also doesn't matter if it represents the final product, since maybe you use InDesign or something similar anyway. Or maybe you just take notes.
Personally, I don't think it's that bad. But again it depends on expectations.

But I do agree that there needs to be a setting for the font and also the font size.

Here's a suggestion from my side (with some random example values):

~~~yaml
page_width: 70 # previously 'lineWidth'
page_lineHeight: 1.6 # [1]
body_font: Calibri
body_fontSize: 20
heading_font: Cambria
heading_fontSize: 28 # [2]
code_font: Consolas # [3]
code_fontSize: 20
~~~

- `[1]` I don't know if it's a good idea to set the line height for each font type individually. I also suggest considering the `line-height-step` property in the future to achieve a *vertical rhythm*. It's supported by Chrome 60+.
- `[2]` Maybe it makes more sense to provide a `fontSize` setting for every heading type (1 - 6). But I think a general `heading_font` setting for all types is just fine.
    - Or what about a percentage setting like `120%` = *120% of `body_fontSize`*?
- `[3]` If you use a proportional font code blocks (and maybe also tables) should still use a non-proportional font that I'd like to define.

I'm using the underscore to separate setting type from the individual setting. Maybe - since it's YAML - it could also be done like this:

~~~yaml
page:
  width: 70
  lineHeight: 1.6
body:
  font: Calibri
  fontSize: 20
# ...
~~~

A setting for `heading_fontWeight` btw. would be a nice extra I think.

---

But I also want to leave a very big "**Thank You**". Caret is the first markdown editor available for Windows that renders the `#`s in it's own column. I know and love this feature from iA Writer but it's only available for macOS.

**Comment by pslobo** [comment]
I agree with @alinnert to some extent. While @ihackalot makes a valid point with

> it defeats the very basic principle of using semantic markup to render a structured document.

the same could be said for every bit of styled text such as italicising text when it's italic, emboldening text when it's bold or the different colour for code etc. If we truly want a text editor that does nothing more that display the markup, then there are other editors out there. Since I more often than not simply look at the editor and not the rendered preview, I appreciate the new heading since it helps me see better the structure of my document.

I wouldn't mind being able to configure the font and such, but I'd prefer to have them as is than revert to previous way.

**Comment by ihackalot** [comment]
I see @alinnert and can't see your point. [Here what Markdown is](https://daringfireball.net/projects/markdown/):

> Markdown is a text-to-HTML conversion tool for web writers. Markdown allows you to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML).
>
> Thus, “Markdown” is two things: (1) a plain text formatting syntax; and (2) a software tool, written in Perl, that converts the plain text formatting to HTML.

Being a _conversion tool_, Markdown documents **don't have to be pretty at all**. Making text look nice and pretty is the job of the UI/UX of your editor in what concerns the styling of the interface and its typography, not the meaning of the document. Sorry if it's unclear, but the context of pretty here is the editor's typography, not the document, in order to convey it's meaning. Otherwise what's the point of structuring it at all? You could just use MS Word like editors.

Additionally, Caret's implementation of this _anti-feature_ is not that great imho. Looking at the attached screenshot you'll see how there's no relationship at all between elements in the way they render. Titles are just an arbitrarily picked typeface at an arbitrarily chosen size. There's apparently no modular scale in place... Text size just increments/decrements in a linear and independent fashion for each element.

![caret-headings](https://cloud.githubusercontent.com/assets/28128/26146653/41c374f8-3af1-11e7-914a-72970fae6d96.png)

All in all, I think the boundary of _pretty_ for Caret must be that of the predefined font preferences set by the user. Good quality fonts will provide a number of variants and sizes to choose from to aid you at displaying _cursive_, and **strong** and `monospace`... But that's all. Everything else I think it's a rendering concern for the theme. So ya, if want it to look good, just pick a nice font.

**Comment by pslobo** [comment]
> You could just use MS Word like editors (if all you want is titles to look like titles, which is not what Markdown is)

Again, the same could be said for **bold**, _italic_ and more. I'm assuming that you would also prefer that Caret simply show you the syntax and not stylise that text. Mind you, I'm not saying it's perfect and obviously the best way to deal with this would be to offer the user a choice (use these headings or not, choose the font for the headings etc.). Then again, apps like iA Writer make certain choices that the user simply has to accept (or choose another app).

Personally, the plethora of markdown editors I've used in the past adhere somewhat to the principal you're defending (and with which I agree to some extent), and therefore at first, the change felt odd. Now however, I quite appreciate it.

I guess the idea behind this is, as with almost all other tweaks such as syntax highlighting, stylising text etc. is to facilitate reading and quickly understanding what is on the digital page. Yes, we could have a plain editor and then toggle preview for that, and no, they will never satisfy everybody, but what I really appreciate about Caret and its developers is their willingness to discuss these types of things with the users, listen and iterate. I have little doubt that with all our input, Caret will quickly become the best editor around.

On a side note, which font is that you're using?

**Comment by ihackalot** [comment]
I think I understand what you say @pslobo but... nope, allow me to disagree, although I do agree that at the extremes boundaries get real thin 😄 

> Again, the same could be said for bold, italic and more.

Again, this is **not true**.The nature of **bold** and _italic_ is prosodic stress which, in linguistics, it means the relative prominence given to a certain syllable in a word, or to a certain word in a phrase or sentence, to convey meaning that otherwise could not be captured in written form.

Headlines, on the other way, where introduced just in the last century, when increased competition between newspapers led to the use of attention-getting headlines. So headlines are text indicating the nature of the article, and therefore the meaning of the document.

You would eventually yell in bold, but you wouldn't set it a heading. A title is still different, and for that good typefaces provide you with titling capitals, which are a variant of uppercase designed especially for heading and titles.

So my point is that you should be allowed to structure text to give it meaning, as of the intent of Markdown (thus giving some visual cue, whatever you like), and leave it to rendering the job of convey the meaning of the document.

**Comment by pslobo** [comment]
With that thorough explanation and lesson I concede victory and stand corrected. 😁

**Comment by ihackalot** [comment]
I'm glad @pslobo Thank you for giving me the opportunity to clarify to myself what I meant 😄  Although I'd better like to be wrong and have my typography set again as it should instead. Would you please join me to convince developers? 😃

**Comment by pslobo** [comment]
@erusev and @astoilkov this request should happen 😁 

On a more serious note, I think that a good middle ground, and pretty much in line with the flexibility of Caret would be to have settings for this. Things like:

```
styled_headings: true | false
styled_headings_font: Fancy Font Regular
styled_headings_size: 120%
```

Obviously we have no way of knowing how complex this would be to achieve so as always, we've made our voice heard, now the decision is in your capable hands.

Also, @ihackalot what font are you using in the above example, I liked it.

**Comment by ihackalot** [comment]
@pslobo that might work, but could also be the door to a stylistic hell.
What about plain text as before, as default (so you damn pay me a dime for that lesson before 🤣 and make me happy) and then you [take the path of Deckset](https://www.decksetapp.com/) instead, and create very nice looking themes? This would make this all happy I guess, as it would ensure great balance across the board, and some degree of freedom to the fancy people 😄 

@pslobo your proposal is too close to that of @alinnert which honestly I see as too overly complicated. You shouldn't tinker that much with typography, it will give you headaches and not even make you look cool.

@pslobo I apologize, the font request thing just slipped through 😭  I'm using [Operator Mono](https://www.typography.com/blog/introducing-operator).

**Comment by alinnert** [comment]
@ihackalot what do you think about the way iA Writer went? Pre-defining the font settings completely? At least I think they did that. I don't know it that well. But some time ago I found they use a specific font. (unfortunately I can't find it right now). I'd also take that if looks nice.

**Comment by pslobo** [comment]
I'd be ok with the path akin to iA Writer or Deckset, where the developers choose a sensible mix of design styles and the user either accepts them or moves on. I certainly don't want to see Caret go down the same path as Sublime Text (one could spend a week tweaking all those settings).

Thanks for the font @ihackalot added to my Christmas list 😀

**Comment by ihackalot** [comment]
Well I think iA Writer is a bit off topic here. All I can say is that it's the editor I have currently switched to because:

- this thing with crazy headings 🙄 
- Caret's export not being consistent with preview (see #237)

**Comment by astoilkov** [comment]
Caret now has a way to disable big headings. This could be achieved by going to Preferences and setting the `useLargeFontInHeadings` to `false`.

Closing this issue. Thanks to all the people part of the discussion which explained their point of view - this always helps us improve the product.
