### ISSUE TITLE
Table columns resize incorrectly when typing Chinese characters 

### ISSUE THREAD

**Issue by Reeeeeemi** [careteditor/caret#380]
Caret is pretty elegant and I love it so much, everything has been working perfectly so far except the auto-resizing of table on typing Chinese.
Here is the context I met,
![context](https://cloud.githubusercontent.com/assets/14024960/26355948/0982c358-3ffd-11e7-8d5d-8174e1ea9196.gif)
There two problems when typing Chinese in the table:
* table codes are not aligned correctly.
* extra characters are appended when tying Chinese within table **after Caret auto-generates table snippet**. Note that this wired extra string is a recursively cascaded substring of the characters I typed, like 'zhong' => ‘中’, then the extra characters would be 'zhongzhonzhozhz'. However, copy&paste Chinese works fine.

OS: Windows 10
Caret: 2.0.11
Input method: built-in Chinese input method

**Comment by pslobo** [comment]
The second issue seems similar to what is happening in https://github.com/careteditor/caret/issues/323

**Comment by YongHee-Kim** [comment]
Same with Korean characters too. It seems problem is something to do with double-byte characters.
![korean](https://user-images.githubusercontent.com/7087745/27565790-69fcc862-5b1b-11e7-86de-bd08fd66ca44.gif)

**Comment by massacreformash** [comment]
same issue on macOS

![example](http://d.pr/i/8CAyHL+)

OS: 10.12.5
Caret: 3.2.3
Input method: built-in Chinese input method

**Comment by astoilkov** [comment]
The second issue you described is now fixed in the latest Caret 4.0 Beta release available [here](https://caret.io/4beta/).

However, the first issue can't be fixed because Chinese characters take more space which makes them impossible to align with the columns that have different than Chinese characters inside of them. If you have suggestions or questions do not hesitate to ask us.

Closing this issue.
