### ISSUE TITLE
Feature Request: (Option) Show text blocks justified.

### ISSUE THREAD

**Issue by archfrog** [careteditor/caret#384]
I use Caret more and more.  Recently, I've begun experimenting with using Caret instead of Microsoft Word 2016 because I believe in open and flexible standards.  One thing I miss from Word 2016 is the ability to justify all "normal" text (including bulleted and numbered lists!).  

I know that this is sort of outside of Markdown and Markdown Extra, as neither provides any means of controlling the justification of a block of text (AFAIK).  However, nobody says that the Markdown renderer or viewer cannot use text justification.  In fact, reading justified text is must more pleasant than reading non-justified text, for which reason I'd like to suggest that Caret gets an option to justify text.  

I believe this is a very trivial request but it may possibly be troublesome with the PDF generation part of Caret.

Cheers,
Archfrog/Mikael

**Comment by astoilkov** [comment]
Hi @archfrog,

You can actually achieve this in the preview using a custom theme. You could do the following things:
  1. Click on `View -> Add Theme...` which opens the directory containing preview themes
  2. Copy and paste the `Default.css` theme and name it the way you want
  3. Open the new `.css` file and in the `:host` selector add `text-align: justify;`

Thanks for your feedback. I will close this issue because there is a way to make text justify. Note that we have no plans for introducing text justification in the editor itself.
