### ISSUE TITLE
Multi-line quotes show as single line

### ISSUE THREAD

**Issue by angelsix** [careteditor/caret#390]
> Quote line 1
> Quote line 2
> Quote line 3
> Quote line 4

Shows in preview as

| Quote line 1 Quote line 2 Quote line 3 Quote line 4

**Comment by erusev** [comment]
This is expected.

Content in quotes follows the same rules that content outside of quotes.

The following would also render as 1 line.

```
line 1
line 2
line 3
line 4
```

**Comment by angelsix** [comment]
This doesn't match GitHubs MD rendering. Nor Texts.io or MarkDown Editor or any other on the market. 

No syntax in this works you cannot get any multiline quotes no matter what you type

**Comment by pslobo** [comment]
@angelsix, @erusev is right. According to GitHub's own [Markdown Specs](https://github.github.com/gfm/#block-quotes) (which Caret uses), multiline block quotes are rendered as a single paragraph. You can see this in the few examples they have there. If you want multiple lines in the block quote, then add 2 spaces after each line to force a new line. [CommonMark Spec](http://spec.commonmark.org/0.26/#block-quotes) is the same when it comes to block quotes.

I have a plethora of markdown editors (more than I should actually) and some respect this spec while others render the preview as multiple lines. I suspect that this is a little helper, but the truth is that those apps aren't respecting the spec whereas Caret is.

**Comment by angelsix** [comment]
Ok I read the CommonMarks specs and that to me reads like it should be multiline if each line starts with >

Also that's how GitHub shows it like here

> Line 1
> Line 2
> Line 3

I'm not trying to keep contradicting you it's just it seems every other editor and GitHub and even those specs to me reads like they should be multiline. For example they show each block quote line as a new <p>

**Comment by erusev** [comment]
@angelsix 

Check out http://try.commonmark.org.

Also, GitHub produces multiline output in issues but not in markdown files (ex: README.md files).

**Comment by angelsix** [comment]
Ah ok. No problem. It's funny how yours is about the only editor that follows the rules :)

By the way, I've tried about 7 others, yours is by far the cleanest. Loving it so far

**Comment by pslobo** [comment]
@angelsix most that produce multiline entries do so to facilitate the users life. Often, those are also the same editors that produce a new line/paragraph when you have a new line in the text, even if not followed but two spaces.

Things like Folding Text, Bear, Ulysses, MWeb Pro are all apps that make you life a little easier by making new line in editor == new line in preview (even when the spec says that a <br> happens when the line is followed by 2 spaces.)

iA Writer respects the spec, although you can change this behaviour in settings too. Personally, I prefer to have stricter markdown since this means it should in theory work consistently across editores/viewers etc.

**Comment by BokaiChen-Pony** [comment]
`first line  second line`
