### ISSUE TITLE
Paste image directly

### ISSUE THREAD

**Issue by narnaud** [careteditor/caret#425]
This new feature would probably work well with #423 .

The idea is to be able to paste an image from the clipboard directly in the file: the image will be created close to the file and added accordingly.

Use case:
* Image coming from a web page (select and copy on the browser, paste on Caret)
* Screenshot of an application (saved in the clipboard)

**Comment by erusev** [comment]
I like it. Do you have ideas about how the image files should be named? Thanks.

**Comment by narnaud** [comment]
If #423 is done and enabled, I would:
name_of_md_file-hash.extension
(a hash on 8 characters would be enough IMO)
and save it in the folder the markdown file is.

If not, maybe ask for the name to the user, and save it by default in the folder the markdown file is.

Unfortunately, you have all kind of possible issues if the location is not writable :(

**Comment by pslobo** [comment]
I like both ideas and think it would be a welcomed addition (similar to what 1Writer does on iOS).

I do however see a few issues with this that would need to be addressed.

1. If you create a new file, start writing and then try paste/drop an image onto the newly created file, which isn't yet saved or named, you would need to prompt the user to save the file, otherwise you'll have no way of knowing where to save the image and what to name it;
2. How will you handle images in the clipboard when it comes to their extension? You'll have to have some form of logic testing to see if it's a supported and valid format;
3. Same for dragging images onto Caret. You'd beed to check if their format is supported. Wouldn't make much sense dragging a 20MB TIFF image into a 100Kb markdown file now would it :)

These are just a few issues I can foresee off the top of my head.

So, new settings options would need to be something like:

```yaml
DefaultImageFormat: 'png'
NamingFormat: ###_FileName.ext | FileName_###.ext  
```

**Comment by narnaud** [comment]
Hi @pslobo 

1/ This is a problem indeed, in this case just ask the filename to the user - or maybe disable the feature. To be honest, I always save my file prior to editing, I didn't think about that.

2/ Regarding the image format, normally the clipboard is coming with a MIME type, something like this: 'image/png', 'image/jpeg', 'image/svg+xml'...
So hopefully the extension is known

3/ I don't think the size of the image is a problem: if the user want this image he has a reason. The image won't be embedded in the markdown file anyway.

But overall, I agree with you, such a feature will have some corner cases or people complaining, I would make it optional at first.

**Comment by narnaud** [comment]
There's something similar existing in VSCode:
https://marketplace.visualstudio.com/items?itemName=telesoho.vscode-markdown-paste-image

**Comment by astoilkov** [comment]
We are happy to say we implemented pasting of images in the latest version of Caret.

Closing this issue. Thanks for the ideas and suggestions.

**Comment by GandalfSaxe** [comment]
Is there any way to control the default location of images?
