### ISSUE TITLE
Preview slows down typing with many math expressions

### ISSUE THREAD

**Issue by instanceofme** [careteditor/caret#45]
I'm writing a 10-page (so far) document with about 70 (so far) math formulae, and typing is getting really slow if I keep preview open.

Would you consider, when there are math expressions, adding a small delay like 500 ms without typing before rendering? I'm more OK with no preview rendering while I'm typing than slow typing (letters not appearing for .3-.5s on my Core i5 MacBook Pro).

**Comment by astoilkov** [comment]
We have investigated the issue with high priority. We will include some performance improvements that we think will be enough so we don't introduce a delay for the preview rendering. We will write in this thread when an update for the app is available.

**Comment by instanceofme** [comment]
Great! Thanks

**Comment by instanceofme** [comment]
I don't know if the performance improvement are included in the 1.2.1 but I still get unreasonable slowness (500ms to 2s) in the aforementioned case.

**Comment by astoilkov** [comment]
Is the performance better or the same? If it is the same could you send us the file that you are working on so we could debug it and figure out why the optimizations aren't kicking in.

**Comment by instanceofme** [comment]
It's a bit better.

Also if it can help: it seems that the further down the file I make my edits, the worse it gets.

**Comment by astoilkov** [comment]
This is very interesting. I have just tested the formula given below by pasting it 70 times and in the previous version of the app it isn't responsive at all and in the new version the delay is reasonable. (This is on a 5 year old MacBook Air).

```
$$$
f(x) = \int_{-\infty}^\infty
    \hat f(\xi)\,e^{2 \pi i \xi x}
    \,d\xi
$$$
```

Not sure what is the reason for the little difference on your end. It is possible that the file itself have some specific scenario we are not familiar with. If you want you could send the file for debugging. Otherwise we don't have anything more we can do about rendering performance in live preview for now. We have plans to introduce more advanced mechanism but this will take awhile.

**Comment by instanceofme** [comment]
I can send it to you but I'd rather not paste it publicly, it's course notes and I haven't asked the course author's authorisation. Do you have an email I can send it to ?

**Comment by astoilkov** [comment]
Yes. You could send it to astoilkov@caret.io. Thanks!

**Comment by astoilkov** [comment]
We introduced a delay in the preview for now. In the future we will make the preview always update instantly no matter the size of the document.

Closing this. If you have more questions or suggestions feel free to open a new issue.
