### ISSUE TITLE
Not able to dismiss "Folders not found" notification in 4.0 Beta

### ISSUE THREAD

**Issue by jamipietila** [careteditor/caret#608]
Hi!

I'm not quite sure how I got the "Folders not found" notification in the the 4.0 Beta. And when I got it, I was unable to get rid of it.

It seemed that only way to get rid of the message is to restart the program. I was able ti see menus and files what I opened behind the transparent notification window.

Restarting the program fixed the problem.

**Comment by astoilkov** [comment]
Hi @Jamipietila,

That is really strange because we don't have "Folders not found" notification anywhere in the code. We also don't have code that says "Folders not found" or anything that can concatenate to this.

If the issue happens again please make a screenshot and send it to us so we could investigate it.

Until then I am closing this issue.

Thanks a lot for reporting.

**Comment by jamipietila** [comment]
Hi!

Good that I already did :)

![screen shot 2018-01-15 at 14 52 06](https://user-images.githubusercontent.com/16705804/34945460-2602cf54-fa0c-11e7-9715-81cc7e602dfe.png)

**Comment by astoilkov** [comment]
Aaah. Now I understand. This is recent folders (`Ctrl+R` in the Beta). It can be hidden with `Esc` key.

**Comment by jamipietila** [comment]
Ah thanks :)
