### ISSUE TITLE
plant UML feature request

### ISSUE THREAD

**Issue by rasmusmk** [careteditor/caret#618]
I would like support for UML using plantUML since seems wider use than mermaid. Especially because doxygen supports it :-).
plantUML already have tags for starting and stopping a uml.  @startuml, @enduml

**Comment by astoilkov** [comment]
Hi @rasmusmk,

Are you aware of JavaScript implementation of `plantUML`? I only found [this Java implemention](https://github.com/plantuml/plantuml) but we can't run java in our app because every user will need to install java on their computer to run it.

Thanks for the suggestion.

**Comment by rasmusmk** [comment]
Hi
Can see that is a problem since you would like an independent program which does not rely on other installations. I am not aware of a pure JS implementation of plantUML and at some extend it also needs graphwiz to be installed :-(

**Comment by astoilkov** [comment]
Hi @rasmusmk,

Thanks for the additional information and understanding. I will close this issue because currently there is no way to implement what you suggested. However, if you find a JavaScript implementation of plantUML please do not hesitate to write back here and let us know so we could include it.

Thanks!
