### ISSUE TITLE
Bug: Multiple tabs open for the same file (V4)

### ISSUE THREAD

**Issue by sguergachi** [careteditor/caret#631]
Steps:
1. Open Welcome.md file in Caret Introduction folder
2. Open preferences.md file
3. Click Welcome.md file in file list sidebar whilst viewing preferences.md

We have 2 Welcome.md tabs open, when I expect to be sent to the already open Welcome.md tab.

**Comment by erusev** [comment]
We made it work like this because we like how the browser handles tabs and we wanted to create a similar UX. 

We feel like modern code editors like Visual Studio Code are a bit too eager to help users when they auto-switch the tab as in your example or when they create temporary (italic) files that behave differently than regular tabs. We feel like this behavior adds too much complexity and makes the UX less friendly to less technical users.

We wanted to create a UX that everyone can use - from a technical person that writes complicated documentation to someone that writes a couple of essays per month.

I hope this makes sense.

**Comment by sguergachi** [comment]
Sounds good
