### ISSUE TITLE
Exporting to HTML does not export images.

### ISSUE THREAD

**Issue by canislupaster** [careteditor/caret#692]
(Caret 3.4.6, Windows 10)
When I export to HTML, all images except gifs (I think) are exported. All the others just show up as plain text:
![html image problem](https://user-images.githubusercontent.com/13261878/37629230-d9580bae-2b9a-11e8-8bc3-249f6fcc62f6.png)
The second image is an animated gif. When exporting to PDF, everything seems to work fine.

And in the new 4.0 beta, only the bottom of the menu is clickable, then exporting to HTML doesn't show a choose file dialog.

Otherwise, great editor!

**Comment by canislupaster** [comment]
Ok, I found the issue. Spaces in image paths do not work in the HTML preview or the HTML export, both beta and release. Thanks for constantly fixing things, I would appreciate a fix for this. 😉

**Comment by astoilkov** [comment]
Hi @Thomas-QM,

Actually, a space in the path of an image is an invalid Markdown syntax. You will need to HTML encode spaces with `%20` in order to fix your issue. The latest Caret Beta release will automatically encode paths when using the autocompletion of paths.

Closing this issue. If you have any more questions please do not hesitate to write us back.

**Comment by canislupaster** [comment]
Oh, I never knew that. Thanks. Also I think the autocomplete issue happens when pasting images.

**Comment by astoilkov** [comment]
We fixed the pasting images problem in the latest release. The pasted images no longer include spaces in their names.
