### ISSUE TITLE
Menu and Raw Text

### ISSUE THREAD

**Issue by craigbass76** [careteditor/caret#736]
I grabbed the beta this morning, and have a couple questions. I'm seeing h1 and h2 instead of # and ##. I'd rather see the hashtags than the html-ish looking codes. Did I do something, or is that the default behavior? Can I change it?

Is there a way to ALWAYS have the menu (File, Edit, etc) on without having to hit Alt first? I'm wondering if these are things I can dork with in the preferences file, but haven't found a doc yet on how to do that.

It's not killing me -- I'm using Geany with a markdown plugin, but my employer will want me on Caret as soon as I can get there.

**Comment by astoilkov** [comment]
Regarding the h1 and h2 instead of ###: Yes. This is the default behavior and there is no preference to change this. Do you have any specific reason you want to see the hashtags?

Regarding the menu: No. You should hit Alt. However, you could use the command palette popup to access commands available in the menu. Just hit `Ctrl+Shift+P` to open the popup and search there.

**Comment by craigbass76** [comment]
If I'm coding html, I like to see all the tags. I guess I'm just used to it and figured the markdown editor would be operating sort of the same way. I thought sure I saw it on a screenshare with a coworker, but she's on an older version of Carot; I grabbed the beta.

**Comment by astoilkov** [comment]
Yes. In the current official version 3.6.4 the hashtags are visible. However, we are moving to a new design.

I will close this issue. However, if you have additional questions do not hesitate to write here.
