### ISSUE TITLE
Add graph rendering support

### ISSUE THREAD

**Issue by decanus** [careteditor/caret#876]
It would be useful if I was able to create both mermaid and graphviz graphs in the editor, hackmd for example allows for this and renders them correctly.

```mermaid
sequenceDiagram

Alice->>Bob: INVITE
Bob->>Group: JOIN
Bob->>Group: POST
Alice->>Group: KICK

```

**Comment by astoilkov** [comment]
Hi Dean,

We actually did have mermaid in earlier versions of the app but decided to remove it. The problem was that we would need a lot of time to fix the bugs and make the design of mermaid feel aligned with the app and that didn't seem like a good tradeoff when knowing not a lot of people use that feature.

Thank for the interest in your product.
